### ISSUE TITLE
Allow guards on place-transition arcs

### ISSUE THREAD

**Issue by henriquebastos** [matthewryanscott/CarlAdam#1]
The guard on the transition level does not allow us to control the input of the transition.

As pointed here (Http://hooopo.gitbook.io/petri-flow) a guard is part of an arc and can allow us to control the flow enabling implicit and explicit ORs.

**Comment by gldnspud** [comment]
@henriquebastos I don't think that the two need to be mutually exclusive.

How about we change the ticket to be "Allow guards on PT arcs"? I'll do that now and we can discuss further.

The "vending machine" example was based on the example from the first chapter of [Understanding Petri Nets](https://link.springer.com/book/10.1007/978-3-642-33278-4).

For example, on page 13 here is the diagram and the description of adding preconditions to the occurrence of a transition:

> <img width="592" alt="image" src="https://github.com/matthewryanscott/CarlAdam/assets/163337783/690e5a6b-4b20-4712-8da0-5d5c60480dd5">
>
> Technically, we achieve this with the help of a _parameter_, **x**. The preconditions for the occurrence of a now include an _occurrence mode_, that is, the replacing of **x** with a concrete value. From the marking shown in Fig. 1.10 with the occurrence mode **x=5**, the marking in Fig. 1.11 is reached.
>
> The label **x>0** in **a** states an additional precondition for the occurrence of **a**. It will prevent **a** from occurring, if the counter holds the token “0”.
